name: Daily Selenium Job

on:
  schedule:
    - cron: "22 9 * * *"    # codziennie o 10:25 CEST (8:25 UTC)
  workflow_dispatch:

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests selenium

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i chrome.deb || sudo apt-get install -fy

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'

      - name: Run Python script
        run: python superMegaChadtester.py   # zamień na swoją nazwę pliku
