name: Selenium Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 12 * * *'  # codziennie o 15:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests schedule selenium

      - name: Set up Chrome
        uses: actions/setup-chrome@v3

      - name: Set up Chromedriver
        uses: actions/setup-chromedriver@v3
        with:
          chromedriver-version: 'latest'

      - name: Run tests
        run: |
          python superMegaChadtester.py
