name: Selenium Form Checker

on:
  schedule:
    - cron: '40 12 * * *'  # Uruchamiaj codziennie o 15:00 UTC
  push:
    branches: [ main ]

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests schedule selenium

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run Selenium Form Checker
        run: |
          python superMegaChadtester.py
