name: Daily Selenium Job

# Uruchamiaj codziennie o 7:00 UTC (9:00 czasu polskiego latem, 8:00 zimą)
on:
  schedule:
    - cron:  "25 8 * * *"
  workflow_dispatch:  # umożliwia ręczne odpalenie workflow z interfejsu GitHub

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests selenium

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get install -fy

      - name: Download ChromeDriver (Linux)
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR=$(echo "$CHROME_VERSION" | cut -d '.' -f1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR}")
          echo "Google Chrome version: $CHROME_VERSION -> Pobieram ChromeDriver v$DRIVER_VERSION"
          wget -q -O chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip -q chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/chromedriver

      # Jeśli chcesz uruchomić Chrome w trybie nie-headless, odkomentuj poniższy blok, 
      # aby uruchomić wirtualny ekran Xvfb (oraz upewnij się, że DISPLAY jest ustawiony).
      # - name: Start Xvfb
      #   run: Xvfb :99 -screen 0 1920x1080x24 &
      # - name: Set display (if not headless)
      #   run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Python script
        env:
          # DISPLAY: :99  # jeśli używasz Xvfb i trybu graficznego
         run: python superMegaChadtester.py
