name: Selenium Form Checker

on:
  schedule:
    - cron: '21 13 * * *'  # Uruchom codziennie o 10:45 UTC (dostosuj jeśli potrzeba)
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true

      - name: Run Selenium Form Checker
        run: python superMegaChadtester.py
